Zarathustra/main/urls.py
from django.urls import path
from django.urls import re_path as url
from . import views

urlpatterns=[
    path('register',views.registerPage,name='register'),
    path('login',views.loginPage,name='login'),
    path('logout',views.logoutPage,name='logout'),
    path('new-question',views.newQuestionPage,name='new-question'),
    path('reply',views.replyPage,name='reply'),
    path('',views.homePage,name='index'),
    path('question/<int:id>',views.questionPage,name='question'),
    ]

Zarathustra/mywebsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

Zarathustra/main/models.py
from django.db import models,IntegrityError
from django.contrib.auth.models import User


# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=False)
    body = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.title)

    def get_responses(self):
        return self.responses.filter(parent=None)

class Response(models.Model):
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, null=False, on_delete=models.CASCADE, related_name='responses')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    body = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.body

    def get_responses(self):
        return Response.objects.filter(parent=self)
    

Zarathustra/main/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from .models import Question,Response
class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'email': forms.EmailInput(attrs={
                'required': True,
                'placeholder': 'joe@example.com',
                'autofocus': True
            }),
            'username': forms.TextInput(attrs={
                'placeholder': 'joe',
            })
        }
    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs = {'placeholder': 'password'}
        self.fields['password2'].widget.attrs = {'placeholder': 'confirm password'}

class LoginForm(AuthenticationForm):
    class Meta:
        fields = '__all__'


class NewQuestionForm(forms.ModelForm):
    class Meta:
        model=Question
        fields=['title','body']
        widgets = {
            'title': forms.TextInput(attrs={
                'required': True,
                'placeholder': 'what is error 404?',
                'autofocus': True
            }),
        }

class ResponseForm(forms.ModelForm):
    class Meta:
        model=Response
        fields=['body']
        widgets = {
            'body': forms.TextInput(attrs={
                'placeholder': 'Your Answer'
            })  }

Zarathustra/main/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required

from .models import Question,Response
from .forms import NewQuestionForm,RegisterUserForm, LoginForm,ResponseForm


def registerPage(request):
    form = RegisterUserForm()
    if request.method =='POST':
        try:
            form=RegisterUserForm(request.POST)
            if form.is_valid():
                user=form.save()
                login(request,user)
                return redirect('index')
        except Exception as e:
            print(e)
            raise        
    context = {
         'form': form
    }
    return render(request, 'register.html', context)

def loginPage(request):
    form = LoginForm()
    if request.method == 'POST':
        try:
            form = LoginForm(data=request.POST)
            if form.is_valid():
                user = form.get_user()
                login(request, user)
                return redirect('index')
        except Exception as e:
            print(e)
            raise

    context = {'form': form}
    
    return render(request,'login.html',context)

@login_required(login_url='register')
def logoutPage(request):
    logout(request)
    return redirect('login')

@login_required(login_url='register')
def newQuestionPage(request):
    form=NewQuestionForm()
    if request.method == 'POST':
        try:
            form = NewQuestionForm(data=request.POST)
            if form.is_valid():
                question=form.save(commit=False)
                print(request)
                question.author=request.user
                question.save()
                return redirect('index')
        except Exception as e:
            print(e)
            raise

    context={
        'form':form,
    }
    return render(request,'new-question.html',context)


def homePage(request):
    questions=Question.objects.all().order_by('-created_at')
    context={
        'questions':questions
    }
    return render(request,'homepage.html',context)


def questionPage(request, id):
    question=Question.objects.get(id=id)
    response_form=ResponseForm()
    
    if request.method =='POST':
        try:
            response_form=ResponseForm(data=request.POST)
            if response_form.is_valid():
                response= response_form.save(commit=False)
                response.user=request.user
                response.question=Question(id=id)
                response.save()
                return redirect('/question/'+str(id)+'#'+str(response.id))                
        
        except Exception as e:
            print(e)
            raise
    context={
        'question':question,
        'response_form':response_form,
        
    }
    return render(request,"question.html",context)

@login_required(login_url='register')
def replyPage(request):
    if request.method == 'POST':
        try:
            form = ResponseForm(request.POST)
            if form.is_valid():
                question_id = request.POST.get('question')
                parent_id = request.POST.get('parent')
                reply = form.save(commit=False)
                reply.user = request.user
                reply.question = Question(id=question_id)
                reply.parent = Response(id=parent_id)
                reply.save()
                return redirect('/question/'+str(question_id)+'#'+str(reply.id))
        except Exception as e:
            print(e)
            raise

    return redirect('index')

Zarathustra/main/templates/components/response.html
<blockquote id="{{response.id}}" xmlns="http://www.w3.org/1999/html">
  <div class="response-body">     {{response.body}}</div>
  <div class="updates">
    <div class="votes">
    <button class="up-vote" onclick="handleUpVote({{response.id}})">upvote</button>
    <h6 id="upvotes-{{response.id}}">0</h6>
    <button class="down-vote" onclick="handleDownVote({{response.id}})">downvote</button>
    <h6 id="downvotes-{{response.id}}">0</h6>
        <!--<div class="main">
  <button id="upButton" type="button" onclick="upVote()" class="vote">

    <svg class="upArrow" viewBox="0 0 11.5 6.4" xml:space="preserve">
    <path d="M11.4,5.4L6,0C5.9-0.1,5.8-0.1,5.8-0.1c-0.1,0-0.2,0-0.2,0.1
	L0.1,5.4C0,5.6,0,5.7,0.1,5.9l0.4,0.4c0.1,0.1,0.3,0.1,0.4,0l4.8-4.8l4.8,4.8c0.1,0.1,0.3,0.1,0.4,0l0.4-0.4
	C11.5,5.7,11.5,5.6,11.4,5.4z"/>
    </svg>

  </button>
  <h6 id="scoreCounter"></h6>
  <button id="downButton" type="button" onclick="downVote()" class="vote">

  <svg class="downArrow" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11.5 6.4" xml:space="preserve">
    <path d="M0.1,0.9l5.4,5.4c0.1,0.1,0.1,0.1,0.2,0.1c0.1,0,0.2,0,0.2-0.1
	l5.4-5.4c0.1-0.1,0.1-0.3,0-0.4L11,0c-0.1-0.1-0.3-0.1-0.4,0L5.8,4.8L0.9,0C0.8-0.1,0.6-0.1,0.5,0L0.1,0.4C0,0.6,0,0.7,0.1,0.9z"/>
  </svg>
  </button>
</div>-->
    {% if user.is_authenticated %}
      <button class="reply-button" onclick="handleReplyButton({{response.id}})">reply</button>
    {% endif %}
    </div>
<div class="response-author"> ans by 
   {{response.user.username}} at{{response.created_at}}</div>
</div>
    
    
    <blockquote id="reply-form-container-{{response.id}}" class="reply-form-container">
      {% csrf_token %}
      <form class="reply" method="post" action="/reply" >
        {% csrf_token %}
        <input type="hidden" name="csrfmiddlewaretoken" value="ZyWC09C1wAM9VT1G0JxrLEDEkbaPZRled8CIKZ6dlZ3bzrlFYysm8rAvxnXIKBdw">
        <input type="hidden" name="question" value="{{question.id}}"/>
        <input type="hidden" name="parent" value="{{response.id}}"/>
<div class="inputBox">
        <input type="text" class="effect-1" name="body" placeholder="Your Reply" required="" id="id_body">
    <span class="focus-border">
        <i></i>
    </span>
</div>

          <button class="cancel" type="button" onclick="handleCancelReply({{response.id}})"  class="reply-form-cancel-button">cancel</button>

<input class="reply-form-submit-button" type="submit" value="Reply">
      </form>
    </blockquote>


  {% for children in response.get_responses %}
  {% include 'components/response.html' with response=children %}
  {% endfor %}


    </blockquote>

<!--<script>
    var score = document.getElementById("scoreCounter");
score.innerHTML = "0";
var scoreValue = 0;
checkScore();

function upVote() {
  scoreValue++;
  score.innerHTML = scoreValue;
  checkScore();
}

function downVote(respondID) {
  scoreValue--;
  score.innerHTML = scoreValue;
  checkScore();
}

function checkScore() {
  if (scoreValue < 0) {
    score.style.color = "#FF586C";
  } else if (scoreValue > 0) {
    score.style.color = "#6CC576";
  } else {
    score.style.color = "#666666";
  }
}
</script>-->

Zarathustra/main/templates/homepage.html
{% extends 'layout/page.html' %}
{% block content %}
<div class="question-title text-center">
    <h4> Home</h4>
</div>
{% for question in questions %}

<div class="card-container" ">

      <div class="box">
    <div class="box1"><!--问题卡片-->
    </div>
<!--问题标题-->
      <a class="qtext" href="{% url 'question' question.id %}">
          {{question.title}}</a>

         <hr style="margin: 10px;"><!--卡片间隔-->
        <!--问题描述-->
          <div class="body-ellipse" style="font-size: smaller; color:rgb(66, 74, 83)">{{question.body}}</div>

          <hr style="margin: 10px;"><!--卡片间隔-->

          <div style="font-size: smaller; color:lightslategrey">{{question.created_at}}</div>

    </div>
    
</div>
<hr class="card-hr">

{% endfor %} 

{% endblock %}

Zarathustra/main/templates/layout/page.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plaster&display=swap" rel="stylesheet"> 



<link rel="stylesheet" href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />    <title>QES</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'main/css/styles.css' %}?{% now 'U' %}"
    />
    <script src="{% static 'main/js/main.js' %}?{% now 'U' %}"></script>

  

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    {% include 'navbar.html' %}
    
    <div class="container-fluid content" >
        {% block content %}
    
    {% endblock %}
    </div>
  </main>
       

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>

  </body>
</html>

Zarathustra/main/templates/login.html
<script src="https://code.jquery.com/jquery-2.1.0.min.js" ></script>
{% extends 'layout/page.html' %}

{% block content %}


<div class="page login-page">
  <h1 class="title">ZARATHUSTRA</h1>
<hr  border-color:#5FBB9C;text-align: center">

<form method="POST" action="" class="login-form">
  {% csrf_token %}


  <div class="form-item">
      <p class="formLabel">Username</p>
      <input type="username" name="username" id="username" class="form-style" autocomplete="  " required>
  <span class="error">{{form.username.errors}}</span>
</div>
<hr style="margin: 20px; border-width: 2px; border-color:white">
<div class="form-item">
  <p class="formLabel">Password</p>
  <input type="password" name="password" id="password" class="form-style" autocomplete="  " required id="id_password">
  <span class="error">{{form.password.errors}}</span>
</div>
{% if form.non_field_errors %}

<div class="non_form_errors">
  <span class="error">{{form.non_field_errors.as_ul}}</span>
</div>

{% endif %}

<p class="pull-left"><a href="{% url 'register' %}"><small>Register</small></a></p>
  <input type="submit" class="login pull-right" value="Log In" style="text-align:center;vertical-align:middel">

</form>

</div>
{% endblock %}

Zarathustra/main/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-sm fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <span class="logo">Zarathustra</span></a>

    </div>

          <div class="field" id="searchform">
            <input type="text" value="" id="searchterm" >
            <button type="button" id="search">Search</button>
        </div>

        <div class="list-group"></div>


<!-- By Coding Market -->



    <ul class="nav navbar-nav">

      <li class=" nav-item">

        <a href="{% url 'index' %}" >Home</a>
      </li>

      {% if user.is_authenticated %}   <!--如果
      已经认证-->
      <li class=" nav-item"><a href="{% url 'new-question' %}">New Question</a>
  </li>

  <li class=" nav-item"><a href="{% url 'logout' %}">Exit</a>
    </li>

    {% else %} <!-- 若未登录-->
    <li class=" nav-item"><a href="{% url 'register' %}">Register</a></li>
    <li class=" nav-item"><a href="{% url 'login' %}">Login</a></li>
      {% endif %}



    </ul>
  </div>
</nav>
    <style>

.container{

}

.field {
  display:flex;
  position:realtive;
  width:50%;
  height:50%;
  flex-direction:row;
  box-shadow:
   1px 1px 0 rgb(22, 160, 133),
   2px 2px 0 rgb(22, 160, 133),
   3px 3px 0 rgb(22, 160, 133),
   4px 4px 0 rgb(22, 160, 133),
   5px 5px 0 rgb(22, 160, 133),
   6px 6px 0 rgb(22, 160, 133),
   7px 7px 0 rgb(22, 160, 133);
}

.field>input[type=text],
.field>button {
  display:block;
  font:1.2em 'Montserrat Alternates';
}

.field>input[type=text] {
  flex:1;

  border:0.2em solid rgb(26, 188, 156);
}

.field>button {
  padding:0.6em 0.8em;
  background-color:rgb(26, 188, 156);
  color:while;
  border:none;
}
    </style>

<script>
$(document).ready(function() {
    var artList = "";
    $("button").click(function() {

        //Getting the user entry from serach bar
        var inp = $("input").val();

        //Retrieving JSON from Wikipedia API
        $.ajax({
            url: "https://en.wikipedia.org/w/api.php?format=json&action=query&generator=search&gsrnamespace=0&gsrsearch=" + inp + "&gsrlimit=10&prop=pageimages|extracts&pilimit=max&exintro&explaintext&exsentences=1&exlimit=max",
            dataType: "jsonp",
            success: function(parsed) {
                var result, pages = parsed.query.pages;
              //Display the data to the html
                for (result in pages) {
                    artList += '<a href=' + '"' + 'https://en.wikipedia.org/?curid=' + pages[result].pageid + '"' + 'class=' + '"' + 'list-group-item ' + '"' + '>' +
                        '<h4 class=' + '"' + 'list-group-item-heading' + '"' + '>' + pages[result].title + '</h4>' +
                        '<p class=' + '"' + 'list-group-item-text' + '"' + '>' + pages[result].extract + '</p></a></br>';
                }
                $(".list-group").html(artList);
            }
        });


    });

});
</script>
<script>
$(".btn").click(function(){
  $(".input").toggleClass("active").focus;
  $(this).toggleClass("animate");
  $(".input").val("");
});
</script>

Zarathustra/main/templates/new-question.html
{% extends 'layout/page.html' %}
{% block content %}
<div class="page new-question-page">
  <h1 class="title2">Ask question</h1>



<form method="POST" action="" class="new-question-form">
  {% csrf_token %}


    <h1 class="title3">Your question</h1>
  <div align="center">
    <input type="text" name="title" required="" class="demoInput" placeholder="what's your problem?"  autofocus="" maxlength="200" id="id_title"  >
    </div>
    <span class="error"> {{form.title.errors}}</span>


    <h1 class="title3">Description</h1>
  <div align="center">
  <textarea style="font-family:Microsoft soft " name="body" cols="53" rows="10" required="" id="id_body" placeholder=" Supplement the explanation of the question"></textarea>
    </div>
    <span class="error"> {{form.body.errors}}</span>
  
  <input type="submit" value="submit" class="submit-button"/>



</form>
</div>
{% endblock %}

Zarathustra/main/templates/question.html
{% extends 'layout/page.html' %}
{% block content %}
<div class="page question-page">
  <h1 class="question-title">{{question.title}}</h1>
<hr .card-hr>
<div class="question-body">{{question.body}}</div>
    <hr .card-hr>
<span class="question-author">asked by {{question.author}} |  {{question.created_at}}</span>
<hr .card-hr>
<div class="response-container">

    <h4 class="response-container-heading">
        Responses
    </h4>
    {% if not question.responses.all %}
    <div class="no-response-text"> No responses yet</div>
    {% else %}
      {% for response in question.get_responses %}
        {% include 'components\response.html' with response=response %}

      {% endfor %}  
    {% endif %}
</div>

{% if user.is_authenticated %}

<form action="" class="response-form" method="post">
    {% csrf_token %}

    <textarea style="font-family:Microsoft soft;font-weight: 700 " name="body" cols="53" rows="10" required="" placeholder="Write your answer here"></textarea>

        

      <input type="submit" value="Send" class="submit-button2"/>



</form>
</div>

{% endif %}

</div>
{% endblock %}

Zarathustra/main/templates/register.html
<script src="https://code.jquery.com/jquery-2.1.0.min.js" ></script>
{% extends 'layout/page.html' %}
{% block content %}
<div class="page register-page">
  <h1 class="title">ZARATHUSTRA</h1>


<form method="POST" action="" class="register-form">
  {% csrf_token %}

   <div class="form-item">
      <p class="formLabel">Email</p>
    <input type="email" name="email"  id="email" class="form-style" required>
    <span class="error"> </span>
  </div>
    <hr style="margin: 20px; border-width: 2px; border-color:white">
  <div class="form-item">
    <p class="formLabel">Username</p>
    <input type="username" name="username"  id="username" class="form-style" required >
    <span class="error"> </span>
  </div>
    <hr style="margin: 20px; border-width: 2px; border-color:white">
  <div class="form-item">
    <p class="formLabel">Password1</p>
    <input type="password1" name="password1" id="password1" class="form-style" required >
    <span class="error"> </span>
    </div>
    <hr style="margin: 20px; border-width: 2px; border-color:white">
    <div class="form-item">
        <p class="formLabel">Password2</p>
        <input type="password2" name="password2" id="password2" class="form-style" required >
        <span class="error"> </span>
        </div>
    <hr style="margin: 20px; border-width: 2px; border-color:white">

{% if form.non_field_errors %}
<div class="non_form_errors">
    <span class="error">{{form.non_field_errors.as_ul}}</span>
  </div>
  {% endif %}

  <input type="submit" value="Register" class="register" style="text-align:center;vertical-align:middel">



</form>
</div>
{% endblock %}